### ISSUE TITLE
Breakpoint sound fires on Step while debugging

### ISSUE THREAD

**Issue by Grifplex** [djfoxer/VisualStudioMakeTheSound#2]
I thank you for this extension to fill in audio clues where [vsDingExtension](https://github.com/thecoderok/vsdingextension) stopped support at VS 2015.
The only thing you extensions falls short is that the Breakpoint sound fires not only when a breakpoint is hit but also when a step action completes. This gets old quickly when rapidly stepping through code. Is there a way to filter out simple steps and only play the sound after running?
Thanks, Nick.

**Comment by djfoxer** [comment]
Thank you for your feedback. I think your suggestion is crucial in that case I will investigate it and try to figure out how to fix it. Also that linked project looks interesting, maybe I will be able to implement something new from that repo.

**Comment by djfoxer** [comment]
Ok, I think I have found the solution: https://github.com/djfoxer/VisualStudioMakeTheSound/commit/901544c4bf63227949b977b289421a7c93083df2#diff-41794c332f2ee023241c5e8c910a676a Just need more testing

**Comment by djfoxer** [comment]
Done (PR: https://github.com/djfoxer/VisualStudioMakeTheSound/pull/3) you can check it by downloading new version 0.2.2
