### ISSUE TITLE
Hi, I want to replace the sfx for the breakpoint.

### ISSUE THREAD

**Issue by JayFiraja** [djfoxer/VisualStudioMakeTheSound#5]
Is there a path you can share please for replacing the file?
Thanks in advance!

**Comment by CarnageMarkus** [comment]
https://stackoverflow.com/questions/37848843/where-are-custom-extensions-installed-in-visual-studio

> %LocalAppData%\Microsoft\VisualStudio\ **yourVersion** \Extensions\aao4tlnw.4rr\Audio

for example for me it was:

> %LocalAppData%\Microsoft\VisualStudio\17.0_9a11e714\Extensions\aao4tlnw.4rr\Audio

**Comment by djfoxer** [comment]
In upcoming 0.4.0 release custom sound support will be added. I know, it has took a while :)
